export const COLUMNS = [
  {
    id: "todo",
    label: "To Do",
    dot: "bg-slate-400",
    badge: "bg-slate-100 text-slate-600",
    border: "border-slate-200",
    header: "bg-slate-50",
    dropZone: "border-slate-300 bg-slate-50/60",
  },
  {
    id: "started",
    label: "Started",
    dot: "bg-blue-400",
    badge: "bg-blue-50 text-blue-600",
    border: "border-blue-100",
    header: "bg-blue-50/60",
    dropZone: "border-blue-300 bg-blue-50/60",
  },
  {
    id: "in-progress",
    label: "In Progress",
    dot: "bg-amber-400",
    badge: "bg-amber-50 text-amber-600",
    border: "border-amber-100",
    header: "bg-amber-50/60",
    dropZone: "border-amber-300 bg-amber-50/60",
  },
  {
    id: "review",
    label: "In Review",
    dot: "bg-pink-400",
    badge: "bg-pink-50 text-pink-600",
    border: "border-pink-100",
    header: "bg-pink-50/60",
    dropZone: "border-pink-300 bg-pink-50/60",
  },
  {
    id: "completed",
    label: "Completed",
    dot: "bg-emerald-400",
    badge: "bg-emerald-50 text-emerald-600",
    border: "border-emerald-100",
    header: "bg-emerald-50/60",
    dropZone: "border-emerald-300 bg-emerald-50/60",
  },
];
